### ISSUE TITLE
Site Design and Completion

### ISSUE THREAD

**Issue by akallish** [Tombodil/Trope22#13] opened 2022-08-06 23:24 UTC
08-06 Comments

Hello @Tombodil . I reviewed the latest iteration of the different site sections and we are making progress. I have the following comments :

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Home Page

• All looks good
• Shouldn't Opportunities be Home?

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Experience

• All looks good
• Replace Liz image with one here 
https://drive.google.com/file/d/111SC-KCKQ-dVoXFpgXJfe4VTORLr1P92/view?usp=sharing
• Here is her PDF Bio 
https://drive.google.com/file/d/1Ub0aWxGBMa_Locnl_TKGwsnXa-8PoQvV/view?usp=sharing

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Activating

• All looks good

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Solving

• All looks good
• More solutions does not function and should have a roll over color
• When i shorten the browser width, the type under "Solving through capabilities" run into one another
![Screen Shot 2022-08-06 at 5 52 10 PM](https://user-images.githubusercontent.com/35602533/183268847-18f09ce9-1526-4d0a-8922-16e2d6f370c6.jpg)
• Go to Solutions does not function 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Activating

• All looks good
• On rollover can the whole square be a link?

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Case Stories

• All looks good
• Links to individual projects do not work

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Solving/Aurora

• We really need to fix the carousel as it is a mess
• dots cannot stack on themselves
• Image description should be in light gray, not blue. 
• Maybe description is to the left with the dots but a fixed short width and the dots are below it with some space?

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Publishing

• Should be "Published work on a wide variety of topics.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Publishing/Agile

• Should be "Publishing/Presentation"

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Publishing/Behavioral Design

• Should be "Publishing/Facilitation"

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Publishing/Better Worlds

• Should be "Publishing/Panel Discussion"

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Publishing/Design & the Creation of Value

• Looks good
• Can the section titles be in bold and in black?

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Publishing/Feeding the Lion

• Looks good
• Can the section titles be in bold and in black?

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Publishing/Ishizaki

• Looks good
• Can the section titles be in bold and in black?

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Publishing/Katz

• Looks good

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Publishing/Interviews

• Looks good

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Publishing/Other Publications

• Wrong title. Should be "Trope Collaborative has had the opportunity to edit journals as well as author papers."

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Publishing/Rethinking teams

• Should be Publishing/Presentation

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Publishing/Balaram

• Looks good

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Inspirations

• Should be "Publishing/Presentation"

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Instagram

• Change to "Instagram for a wide variety of moments"

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Interest Areas

• Change to "Interest Areas that inform our practice"
• Good behavior of elements as the browser gets narrower

**Comment by Tombodil** [comment] 2022-08-07 06:24
### SAT FIXES AND CHANGES
Some of the changes took longer then expected: Case Story Page population will start deploying tomorrow. I am also off this Monday and Tue. 

Home Page
- Shouldn't Opportunities be Home?: Changed this to home.

Experience
- Replaced Liz image
- I will be hosting 'full bios / vcf' on the tropesites space tomorrow'

Solving

- More solutions given link
- Go to Solutions given link
- Squares have been changed over to a link on hover-state

Solving through capabilities
- browser sizing improved, this will be smoothed. 

Publishing
- changed title back to "Published work on a wide variety of topics.
- The tiles now work as full links in the rollover state. 

ALL PUBLISHING PROJECTS
- All navigation has been updated and the 'back' / 'next' links have been attached to their respective pages
- all pdf downloads site-wide are being hosted on the ionos server space tomorrow for simplicity, they will then be linked through the site. 

Publishing/Agile
- Changed to "Publishing/Presentation"

Publishing/Behavioral Design
- Changed to "Publishing/Facilitation"

Publishing/Better Worlds
- Changed to "Publishing/Panel Discussion"

Publishing/Other Publications
- Title is: "Trope Collaborative has had the opportunity to edit journals as well as author papers."

Publishing/Rethinking teams
- Changed to Publishing/Presentation

Publishing/Design & the Creation of Value
- there are no section titles.

Publishing/Feeding the Lion
- Section titles are now in bold and in black.

Publishing/Improvisational Design (Ishizaki)
- there are no section titles.

Interest Areas
- Changed title back to "Interest Areas that inform our practice"

Instagram
- Changed title back to "Instagram for a wide variety of moments"

Inspirations
- Is a B level page, mirroring the structure of the home carousel: I can spend the time adding it into the publishing squares and then make it a c level page with a different title structure.

Case Stories
- Links to individual projects do not work except aurora: I'm building these pages. Fixes and adjustments ran from 9pm-1am so I will pick these up tomorrow.

Solving/Aurora
- Carousel given first formatting revision
- dots given width of slide area, single stack
- Image description changed to site color #999
- Description and bullet nav given left full width formatting. Bullets are placed under depth of max description. This scales up past 1k width.

**Comment by akallish** [comment] 2022-08-07 12:37
@Tombodil thanks for doing Al, these refinements. Will review the Aurora carousel changes today and comment.

**Comment by Tombodil** [comment] 2022-08-11 05:13
### Wed Night Fixes
_Was kept late at day work, but got most of the standout issues handled. Full home page module scaling will be done tomorrow due to time constraints._

General Behavior and Layout
- The invisible trigger box for the menu is now much smaller and scales with the dropdown. There shouldn't be any more missed close commands. The page is now no longer being interfered with near as much. (80px height)

- Figured out the left margin weirdness was caused by some sort of css issue with the solving page in specific, adjustments made. All pages Checked.

- fixed Instagram internal scaling issues: there was formatting overlap being caused by the IG frame interacting with the CSS media break points. Simplified to remove issues. 

- Interest Areas full collapsing behavior applied and tested.

- Publishing/Interviews  full collapsing behavior applied and tested.

- Publishing/Other Journals full colapsing behavior based off the interviews code. Tested.

- Gallery img handling given a screen based max height, with imgs now set to contain, with an alignment bias towards the bottom left of the gallery space. This will always align next to the area controls. Height maxes are meant to keep the gallery space a bit more consistent across screen widths.

- Traingle img under asjusting given preliminary scaling. Full home page scaling for tomorrow (thur, 11th) as it is getting late.

**Comment by akallish** [comment] 2022-08-11 11:43
> ### Wed Night Fixes
> 
> _Was kept late at day work, but got most of the standout issues handled. Full home page module scaling will be done tomorrow due to time constraints._
> 
> 
> 
> General Behavior and Layout
> 
> - The invisible trigger box for the menu is now much smaller and scales with the dropdown. There shouldn't be any more missed close commands. The page is now no longer being interfered with near as much. (80px height)
> 
> 
> 
> - Figured out the left margin weirdness was caused by some sort of css issue with the solving page in specific, adjustments made. All pages Checked.
> 
> 
> 
> - fixed Instagram internal scaling issues: there was formatting overlap being caused by the IG frame interacting with the CSS media break points. Simplified to remove issues. 
> 
> 
> 
> - Interest Areas full collapsing behavior applied and tested.
> 
> 
> 
> - Publishing/Interviews  full collapsing behavior applied and tested.
> 
> 
> 
> - Publishing/Other Journals full colapsing behavior based off the interviews code. Tested.
> 
> 
> 
> - Gallery img handling given a screen based max height, with imgs now set to contain, with an alignment bias towards the bottom left of the gallery space. This will always align next to the area controls. Height maxes are meant to keep the gallery space a bit more consistent across screen widths.
> 
> 
> 
> - Traingle img under asjusting given preliminary scaling. Full home page scaling for tomorrow (thur, 11th) as it is getting late. 

@Tombodil i am happy these glitches were solved creating a better user experience.

**Comment by Tombodil** [comment] 2022-08-12 05:36
**Thur Night Fixes**
_just some minor cleanup before the formatting changes for screen scaling_

Home Page Titles
- Given 40px height, this scales up a bit from mobile sizes and is far smaller for large screen sizes. Main header titles are 24px so 40px seemed like a natural step up.

- Main content area margins paired with the new compression logic

- Fixed a margin bug between 1190px and 900px.

**Further Changes** 
_formatting changes, media hooks installed and smallest / largest state now intact. **I wouldn't look at this yet:** the breakdown is garbled because I don't have the middle states setup yet. It's not broken, it's just missing logic between 900 - 1300px, which will be completed tomorrow. Ran late on time tonight. _

- Mobile scaling for home page given first pass, most pages already given mobile reduction logic. 

- I now need to check all pages and adjust layout transitions between 900 and 1200 px

**Comment by akallish** [comment] 2022-08-12 11:54
@Tombodil thank you for detailing the pages and trying to optimize for mobile. When can we do one more walk through? 

Also apply the new masthead to the blog.

Thanks.

**Comment by Tombodil** [comment] 2022-08-12 13:47
Pry sat night. I'll be getting the last couple slides done tonight and then
review the rest of the pages one last time.

**Comment by Tombodil** [comment] 2022-08-12 23:59
**FRI EVENING UPDATE**
_I 'had' the day off from work. I modified and tested formatting 12 hrs between last night and today, It's functional, it works mobile, there is some minor weirdness in a few spots but its much better. I took it from 'busted and unworkable' to 'mostly pretty good' . We're nearly at the limits of forcing Squarespace's cms backend into shape, as some of their internal content handling is done in iFrames, which are dynamically defined._

MOBILE AND SCALING
------------------------------------------------
HOME PAGE
- Opportunity Carousel already scales do to minimal elements: VERIFIED
- Experience 1 given scaling logic + mobile formatting: VERIFIED
- Experience Adam: given scaling logic + mobile formatting: VERIFIED
- Experience Liz: given scaling logic + mobile formatting: VERIFIED
- Activating 1 given an img adjustment for mobile sizing. Needed because the black arrow intersects with the type at under 900px; VERIFIED
-Activating 2: Resampled and adjusted the triangle across all widths: removed bugs: VERIFIED

B LEVEL
- Solving: VERIFIED
- Publishing: VERIFIED
- Inspiration: VERIFIED
- Interest Areas: VERIFIED
- Instagram VERIFIED

C LEVEL
- All Publishing Pages given adjustment logic: VERIFIED
- Interviews Page Type given adjustments logic: VERIFIED
- Other Publications page type given adjustment logic: VERIFIED
- Solving given adjustment. I had to fight a LOT with Squarespace's iframe based carousels that want to crop. I've gotten it about as good as I can, and they work for mobile sizing and main sizing. They work regardless, but there's page adjustments between 1100px and mobile (sub 800px) where it's sized a bit weird to avoid img cropping. No one should see this, as no one is using this site at 900px browser width. Squarespaces's mobile handling is pretty rough for carousels. I've made it better within their code limitations. 


Known issue:
- Squarespace doesn't like hosting a vcf download. I may have to host it somewhere else like a Dropbox that will create a download link. I will check on this.

Other Steps despite feedback:
- Blog changes
- Decoupling the domain from WIX tomorrow and attaching it to Squarespace as soon as it's cleared.

**Comment by akallish** [comment] 2022-08-13 16:49
08-13 Comments

Hello @Tombodil . I reviewed the latest iteration of the different site sections and we are making progress. It is almost perfect. Gave you a VCF link, some typos, the mobile version of case story images are too small, and an instagram problem.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Home Page

• All looks good 
• Mobile version good

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Experience

• All looks good 
• Mobile version good

• VCF card link
https://www.mediafire.com/file/5wlwha74gmpbdw2/Adam_Kallish_TropeCollaborative.vcf/file

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Activating

• All looks good 
• Mobile version good

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Solving

• All looks good 
• Mobile version good

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Activating

• All looks good 
• Mobile version good

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Case Stories Landing Page

• All looks good 
• Mobile version good

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Solving/Aurora

• All looks good 
• Mobile version : The jpegs do not go all the way across. Losing 20% resolution.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Charlie Trotter

• All looks good 
• Mobile version : The jpegs do not go all the way across. Losing 25% resolution.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
File Restore

• All looks good 
• Mobile version : The jpegs do not go all the way across. Losing 20% resolution.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Future Forward

• All looks good 
• Mobile version : The jpegs do not go all the way across. Losing 50% resolution.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Guided Support

• All looks good 
• Mobile version : The jpegs do not go all the way across. Losing 50% resolution.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Henry Darger

• All looks good 
• Mobile version : The jpegs do not go all the way across. Losing 50% resolution.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Heuristic

• Change title to "IBM Heuristic Analysis"
• Mobile version : The jpegs do not go all the way across. Losing 50% resolution.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
IBM Application

• Change title to "IBM Application Analysis"
• Mobile version : The jpegs do not go all the way across. Losing 50% resolution.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
ID Analysis

• Change title to "IBM Information Documentation Analysis"
• Mobile version : The jpegs do not go all the way across. Losing 50% resolution.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Jellies

• All looks good 
• Mobile version : The jpegs do not go all the way across. Losing 50% resolution.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
LOP

• Change title to "Linux on Power"
• Mobile version : The jpegs do not go all the way across. Losing 50% resolution.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Nexum

• All looks good 
• Move 4th example to second position
• Mobile version : The jpegs do not go all the way across. Losing 50% resolution.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Posters

• Change title to "IBM Posters"
• Move 4th example to second position
• Mobile version : The jpegs do not go all the way across. Losing 50% resolution.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Randallstown UDAT

• All looks good 
• Mobile version : The jpegs do not go all the way across. Losing 50% resolution.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Smartcare

• All looks good 
• Mobile version : The jpegs do not go all the way across. Losing 50% resolution.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
WW Grainger

• Change title to "WW Grainger Safety Manager"
• Mobile version : The jpegs do not go all the way across. Losing 50% resolution.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
ZeroZero

• All looks good 
• Mobile version : The jpegs do not go all the way across. Losing 50% resolution.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
iARM

• All looks good 
• Mobile version : The jpegs do not go all the way across. Losing 50% resolution.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Publishing

• All pages look good
• Interviews : Mobile version the images are too small. Increase by 50%

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Publishing/Other Publications

• Wrong title. Should be "Trope Collaborative has had the opportunity to edit journals as well as author papers."

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Inspirations

• Looks good 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Instagram

• Mobile version does not stack images

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Interest Areas

• Looks good

**Comment by Tombodil** [comment] 2022-08-14 03:44
### SAT UPDATE
_Fixes and initial pass on case story img scaling. I will be turning off the wix domain tomorrow and directing it to the squarespace site as soon as it takes effect._ 

• VCF card link
- Thanks for the vcf. Updated and confirmed working.

ALL CASE STORIES
- Mobile version : The jpegs do not go all the way across.
- I made initial adjustments for the carousel areas specifically under 900px. The current setting is a compromize between taller and shorter images. Currently, 90% of the imgs now cross the entire area. If I increase this any farther, the black area above most of our images becomes massive. I can't do page specific formating for carousels with Squarespace's dynamic system. 

Heuristic
- Title is now "IBM Heuristic Analysis"

IBM Application
- Title is now "IBM Application Analysis"

ID Analysis
- Title is now "IBM Information Documentation Analysis"

LOP
- Title is now "Linux on Power"

Nexum
- Changed example to second position

Posters
- Title is now "IBM Posters"
- Changed example to second position

WW Grainger
- Title is now "WW Grainger Safety Manager"

Publishing
- Interviews : Mobile version image increased for visibility.

Publishing/Other Publications
- Title changed to "Trope Collaborative has had the opportunity to edit journals as well as author papers."

Instagram
![Instagram example](https://user-images.githubusercontent.com/36061390/184521529-b8d458cd-adb2-4bda-872d-5a39724fd310.png)
• I attached a screenshot. I'm currently seeing a 2-img wide grid. If you can screenshot what you're seeing it could help me replicate it.

**Comment by akallish** [comment] 2022-08-14 11:31
@Tombodil great updates. Will look at the instagram. Let's launch.

**Comment by Tombodil** [comment] 2022-08-15 20:26
http://blog.tropesites.com/
First pass on the Blog Header change.

**Closed as completed** 2022-08-18 04:22 UTC
