### ISSUE TITLE
Domain Transfer

### ISSUE THREAD

**Issue by akallish** [Tombodil/Trope22#5] opened 2022-05-05 13:16 UTC
Hello Tom:

I see we have not transferred our domain to SquareSpace and assume that we will not until the build in it is complete and we can then transfer and turn it on?

Thanks,
Adam

**Comment by Tombodil** [comment] 2022-05-05 17:17
Correct. 
Once we  get the site ready to be live we can set up the domain systems. I've checked out the process. 
I'll have to release the domain in the wix account and then attach it to the squarespace site once we're about ready to go.

**Comment by Tombodil** [comment] 2022-08-15 20:27
Process started, only 14 hours in. 

Still processing - this is normal. If there's no change by tomorrow afternoon I'll reach out to ionos and squarespace.

**Comment by Tombodil** [comment] 2022-08-16 19:10
### Update - Tue 16th

Site is launched. looks good.  SSL warning will be in effect for around 48 hours. Please read below.

www.tropecollaborative.com/

**Clerical SSL Issue**
Squarespace registers an SSL certificate when a third party domain is connected to their server space. This process started a few hours ago when the domain finished connecting. Unfortunately this can be up to another 48 hours wait. For the next day or so, the site is live and works fine, but google and many other browsers will kick off a warning screen that requires a user to 'continue to site'. 

As stated above, this is processing and should automatically generate a correct SSL extention once the process is completed. 

I'll check this tonight, tomorrow and Thur to confirm that the SSL certificate is activated by Squarespace, and I'll update you once it's settled.

**Comment by akallish** [comment] 2022-08-16 23:11
Hey @Tombodil Thanks for the update.

I reviewed the site through my phone and it is well done. Most pages load in a stacked fashion.

There are a few problems:

- on the upper right there is something that looks like a hamburger but it is not (two horizontal lines). Can we get rid of this?
- on my bio page the linked in and vcf get cut off
- on activating with the triangle diagram the dots are right below the black line. can we get more buffer space?
- the second diagram shows up all distorted and is a disaster
- solving second carousel the headers are far from the horizontal lines. Could these headers be slightly larger?
- tags in solutions and inspirations are blue on blue. How can we make them white on blue?
- Inspirations tag. The last tag goes on the next line with no white space buffer. Can this be fixed?

**Comment by Tombodil** [comment] 2022-08-17 03:18
### MOBILE FIXES, TUE 16th

HOME
-Fixed initial page margin bug, this will help layout. 

Experience 1
- Fixed a margin issue with first paragraph. Spacing is better.

Experience 2: Adam
- Margins adjusted for bio have been combined with a necessary breakpoint paragraph reduction. Compromise to fit the longer bio on mobile sizes. 
- Links now show for VCF and Linkedin



Activating 2: Triangle
- Max width and height on the Triangle Diagram lowered by 75px to create more space.
<img src="https://user-images.githubusercontent.com/36061390/185026426-198f46b3-5b62-46fb-855f-a13dbb43da11.jpg" width=200px>

Activating 3: Process Diagram
- Declared a width and min-height in order to overwrite any auto formatting.
<img src="https://user-images.githubusercontent.com/36061390/185026449-75e1a96f-d2ec-46f7-b0d2-7632496cd6d0.jpg" width=200px>

Solving 1
- Left and Right aligned content given specific widths and logic. Fixed the stuff stacking. Is now in correct two column layout.

Solving 2
- Brought the spacing down on the headers, fit content to page. 

Solutions and Inspiration Tag Sort buttons
- Tags in solutions and inspirations are now white blue. 
- Deactivated state is now light grey on grey. Defaults back to white on blue when reset.
- tags brought down in size and given a bottom margin that matches right margin. Confirmed aligned on my end.
<img src="https://user-images.githubusercontent.com/36061390/185027217-d9f743fc-87ea-4eaf-b9ea-da5db7cfeb01.jpg" width=200px>

Possible Outstanding Issues
- "on the upper right there is something that looks like a hamburger but it is not (two horizontal lines)"
- I can't replicate this. I fixed some margin issues under 800px so hoping this solves the issue. Could you screenshot from your phone so I can see this? It would help me trace back the issue. I'm not seeing it on my phone or live with the browser set to min width.

**Comment by Tombodil** [comment] 2022-08-17 03:57
Possible Outstanding Issues
- "on the upper right there is something that looks like a hamburger but it is not (two horizontal lines)"
- The screenshot gave me the vague impression the two lines were based on the hidden dropdown menu width. I've given this a padded page width when open. I am wondering if this change will 'push back' those lines into not showing.

**Comment by Tombodil** [comment] 2022-08-19 03:05
update:

Good news, 
the SSL certificate registered and applied. 
Site is shown as secure across all devices now. 
URL prefix changed to 'https'

https://www.tropecollaborative.com/

Site is fully launched. Let me know about the prior fixes when you have time. Then we can close out the github issues, talk pay and move on to the miniatures project.

**Comment by akallish** [comment] 2022-08-19 11:41
@Tombodil perfect

**Comment by Tombodil** [comment] 2022-08-19 20:09
Everything is nice and closed out. If there are any issues with the site or anything breaks in the next few weeks, let me know and I'll fix it, no charge. As standard with my work you get two weeks of bug fixes and site checking just to make sure the site launch goes smoothly.

**Closed as completed by Tombodil** 2022-08-19 20:09 UTC
